CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_OLED=y
CONFIG_OLED_SSD1306=y
CONFIG_I2C=y
CONFIG_ZMK_WPM=y
CONFIG_WORK_QUEUE_STACK_SIZE=2048
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE=y
CONFIG_BT=y
CONFIG_SOC_NRF52840=y
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y
